local item_sounds = require("__base__.prototypes.item_sounds")

-- Add module effect in data-final-fixes to prevent other mods from incorrectly classifying parallel modules as efficiency modules
data:extend({
  -- {
  --   type = "module-category",
  --   name = "parallel"
  -- },
  {
    type = "module",
    name = "parallel-module",
    icon = "__parallel-module__/graphics/icons/parallel-module.png",
    icon_size = 64,
    subgroup = "module",
    category = "parallel",
    tier = 1,
    order = "e[parallel]-a[parallel-module-1]",
    inventory_move_sound = item_sounds.module_inventory_move,
    pick_sound = item_sounds.module_inventory_pickup,
    drop_sound = item_sounds.module_inventory_move,
    stack_size = 50,
    weight = 20 * kg,
    effect = {},
  },
  {
    type = "module",
    name = "parallel-module-2",
    icon = "__parallel-module__/graphics/icons/parallel-module-2.png",
    icon_size = 64,
    subgroup = "module",
    category = "parallel",
    tier = 2,
    order = "e[parallel]-b[parallel-module-2]",
    inventory_move_sound = item_sounds.module_inventory_move,
    pick_sound = item_sounds.module_inventory_pickup,
    drop_sound = item_sounds.module_inventory_move,
    stack_size = 50,
    weight = 20 * kg,
    effect = {},
  },
  {
    type = "module",
    name = "parallel-module-3",
    icon = "__parallel-module__/graphics/icons/parallel-module-3.png",
    icon_size = 64,
    subgroup = "module",
    category = "parallel",
    tier = 3,
    order = "e[parallel]-c[parallel-module-3]",
    inventory_move_sound = item_sounds.module_inventory_move,
    pick_sound = item_sounds.module_inventory_pickup,
    drop_sound = item_sounds.module_inventory_move,
    stack_size = 50,
    weight = 20 * kg,
    effect = {},
  },
})
